version: '2'

services:
  webapp:
    image: "companion-webapp-gateway"
    mem_limit: 512m
    ports:
     - "8080:8080"
    expose:
     - "5701"
     - "54327"
    networks:
      comnet:
        aliases:
         - webapp
  nlp:
    image: "companion-nlp-micro"
    mem_limit: 512m
    expose:
     - "5701"
     - "54327"
    networks:
     - comnet
  nlg:
    image: "companion-nlg-micro"
    mem_limit: 250m
    expose:
     - "5701"
     - "54327"
    networks:
     - comnet
  wordnet:
    image: "companion-wordnet-micro"
    mem_limit: 250m
    expose:
     - "5701"
     - "54327"
    networks:
     - comnet
  classification:
    image: "companion-classification-micro"
    mem_limit: 250m
    expose:
     - "5701"
     - "54327"
    networks:
     - comnet
  sentiment:
    image: "companion-sentiment-micro"
    mem_limit: 200m
    expose:
     - "5701"
     - "54327"
    networks:
     - comnet
  dialogmanager:
    image: "companion-dialogmanager-micro"
    mem_limit: 250m
    expose:
     - "5701"
     - "54327"
    networks:
     - comnet
  webui:
    image: "companion-ui"
    mem_limit: 250m
    expose:
     - "80"
    ports:
     - "8081:80"
    networks:
     - comnet
  jena:
    image: "stain/jena-fuseki"
    mem_limit: 512m
    expose:
     - "3030"
    ports:
     - "3030:3030"
    environment:
     - ADMIN_PASSWORD=1afbda62-8ec9-47a3-a96f-40b58b13c150
    networks:
      comnet:
        aliases:
          - jena

networks:
  comnet: