version: '2'
services:
  webapp:
    image: "companion-webapp-gateway"
    ports:
     - "8080:8080"
    expose:
     - "5701"
     - "54327"
  nlp:
    image: "companion-nlp-micro"
    expose:
     - "5701"
     - "54327"
  nlg:
    image: "companion-nlg-micro"
    expose:
     - "5701"
     - "54327"
  wordnet:
    image: "companion-wordnet-micro"
    expose:
     - "5701"
     - "54327"
  classification:
    image: "companion-classification-micro"
    expose:
     - "5701"
     - "54327"
  sentiment:
    image: "companion-sentiment-micro"
    mem_limit: 150m
    expose:
     - "5701"
     - "54327"
    environment:
     - JAVA_OPTIONS=-Xmx32m
  dialogmanager:
    image: "companion-dialogmanager-micro"
    expose:
     - "5701"
     - "54327"
  jena:
    image: "stain/jena-fuseki"
    ports:
     - "3030:3030"
    environment:
     - ADMIN_PASSWORD=1afbda62-8ec9-47a3-a96f-40b58b13c150