version: '2'
services:
  webapp:
    image: "companion-webapp-gateway"
    ports:
     - "8080:8080"
    expose:
     - "5701"
     - "54327"
  nlp:
    image: "companion-nlp-micro"
    expose:
     - "5701"
     - "54327"
  wordnet:
    image: "companion-wordnet-micro"
    expose:
     - "5701"
     - "54327"
  classification:
    image: "companion-classification-micro"
    expose:
     - "5701"
     - "54327"
  sentiment:
    image: "companion-sentiment-micro"
    expose:
     - "5701"
     - "54327"